### ISSUE TITLE
Renaming writing and parsing methods

### ISSUE THREAD

**Issue by Unaimend** [kerrycobb/nim-dna-seq#5]
Since we will be working with a lot of different file formats it would make sense to have a simple naming scheme.

At the moment we sth. like
`parseFastaAlignmentStream`
`parseFastaAlignmentString`
but I think it is unnecessary  to mention the type of the input which is parsed since the nim type system will choose the correct one.

Also for the 'writing' methods we have stuff like 
`writeFastaAlignmentString`
`writeFastaAlignmentStringToFile`
because so methods can only be called for existing objects I think we could call them sth. like
`toString` and
`writeToFile`

But I am pretty sure there are better ways for a naming scheme.

**Comment by kerrycobb** [comment]
Good points and good ideas. I think it's worth exploring better options so feel free to make changes. I don't have any strong opinions. My main goal with all of the code we have so far was just to try out the 8 bit integer scheme. I have not put much thought into the rest of it.

**Comment by Unaimend** [comment]
Ok, I will look into different libraries and get a little inspiration.
